#B17_QU3U3.py

class QU3U3:
    pass

# Google search on QU3U3

# MALADJUSTED MR. DARCY.Karkat|11|Alternia THE HEFT OF MY FASHIONABLY EXISTENTIAL ENNUI IS FRANKLY STAGGERING, BUT DO TRY NOT TO BE INTIMIDATED.

# GOD WH4T 4 PR3T3NT1OUS QU3U3 T4G

# THIS HAS THE WORD PRETENTIOUS IN IT. I PRESUME IT IS ABOUT ME.

# 5 YEARS AGO 3 NOTES VIA
# https://hosteriumfictus-blog.tumblr.com/post/166650029893/inverumlibertas-god-wh4t-4-pr3t3nt1ous-qu3u3